### ISSUE TITLE
Make it easier to use custom rules

### ISSUE THREAD

**Issue by codecholeric** [societe-generale/arch-unit-maven-plugin#1]
Thanks a lot for the cool initiative to create this plugin :smiley: 

As far as I can see, you have to add arch-unit-maven-plugin to your dependencies and implement `ArchRuleTest` if you want to execute your own rules?

I think it would be cool to allow to specify something like

```
<rule>
    <class>com.my.CustomRule</class>
    <check>
        <package>com.my.app</package>
        <scope>main</scope>
    </check>
</rule>
```

Especially since the classes to import maybe vary under certain conditions (projects are pretty diverse...).

Yes, I know, a PR would be nicer, but I'm completely full at the moment :frowning_face:

**Comment by codecholeric** [comment]
In particular since that would allow sth. like

```
<plugin>
  <artifactId>arch-unit-maven-plugin</artifactId>
  <configuration>
    <rules>
        <rule>
            <class>com.my.CustomRule</class>
            <check>
                <package>com.my.app</package>
                <scope>main</scope>
            </check>
        </rule>
    </rules>
  </configuration>
  <dependencies>
        <dependency>
            <artifactId>my-company-rules</artifactId>
        </dependency>
  </dependencies>
</plugin>
```

:smiley:

**Comment by vincent-fuchs** [comment]
agreed for the ```dependencies``` block within the plugin declaration, we should update the doc showing that way of doing.

Regarding  the ```check``` block in ```rule``` : 
- do you mean to say that ```com.my.CustomRule``` should apply only to classes in ```com.my.app``` package ? 

- what about the ```scope``` ? would ```main``` map easily to "any" main directory like ```src/main/java``` or ```src/main/kotlin```, automatically ? or is it easier to ask the "root path" entirely in the rule config (so that we can mention ```src/main/java``` or ```src/test/kotlin``` (or something entirely different) for instance ?

**Comment by codecholeric** [comment]
Sorry, I was a little tired when I wrote that, just realized that I left out some stuff necessary to understand what I mean.

* yes, I thought about the package. Suppose you have `com.mycompany.DomainRules` in your `mycompany-archrules` dependency, you might want to specify `<check><package>com.mycompany.specificapp.domain</...` for the specific rule. I guess in the current implementation you would set the root path to `target/classes/com/mycompany/specificapp/domain`, right?
* with `main` I simply meant production classes. I don't know if you need to distinguish Kotlin from Java, but it is a typical use case to distinguish rules for classes in `main` from rules in classes for `test`. Sure, alternatively you could give the target root dir, which would probably be something like `target/classes` then, right? Considering usability I think specifying "I want to test production classes" and that's it, is nicest :wink: 

The problem with the `check` method of a class is, that `check` needs to know about which classes to import (except for the root path). I think it would be easier to distribute, if the classes to import would be completely supplied by the plugin, because then the rule could be flexibly applied to different projects.

Maybe similar to the JUnit style, without the need to implement any interface I write

```
class MyDomainRules {
    static ArchRule custom_rule_one = classes()...
    static ArchRule custom_rule_two = classes()...
}
```

and in the plugin I could specify

```
<plugin>
  <artifactId>arch-unit-maven-plugin</artifactId>
  <configuration>
    <rules>
        <rule>
            <class>com.MyDomainRules</class>
            <fields>
                <field>custom_rule_one</field>
                <field>custom_rule_two</field>
            <fields>
            <check>
                <package>com.my.app</package>
                <scope>main</scope>
            </check>
        </rule>
    </rules>
  </configuration>
  <dependencies>
        <dependency>
            <artifactId>my-domain-rules</artifactId>
        </dependency>
  </dependencies>
</plugin>
```

Or leave the fields block out and take all rules declared in the class (which is what I meant by my example).

The plugin could take care of importing `com.my.app` scope `main` once and evaluating the specified rules. Of course I don't know how that would really feel for users, my mind just starts spinning some ideas :wink: 

I just think from an API point of view if I want to write and distribute my own rules then at the moment I would need to depend on `ArchRuleTest` and `ArchUtils`. With the above approach I could write plain ArchUnit and apply my rules with the `archunit-maven-plugin` without any further dependencies in my custom rule code.

**Comment by vincent-fuchs** [comment]
OK, I think I get it. 

I think we should try to cater to 2 use cases : 

- use "preconfigured rules" which is the current one implemented. we could probably rename the current ```rule``` element into a ```preconfigured-rule``` though, to be more explicit. That would be a breaking change, but it's OK : we don't have that much success yet ;-)

- have a new "rule to configure" concept (with a ```configurable-rule``` element ?), for which we can provide config "at runtime", as suggested by @codecholeric. 

Both could be part of the ```rules``` block, so that we can mix and match. 

For the new ```configurable-rule``` : 
- default scope should be "main" - can be overridden with scope=test if required.
- by default, through introspection, get all the static ArchRule fields, from the class, so that we don't need to specify. Allow (maybe as an evolution later) to specify the list of "checks" to be performed. 

so we could get something like : 

```
                    <rules>

                        <!-- current use case - just have to rename from rule to preconfigured-rule -->

                        <preconfigured-rule>com.societegenerale.commons.plugin.rules.NoJunitAssertRuleTest</preconfigured-rule>

                        <configurable-rule class="com.MyDomainRules">

                            <!-- by default, will get all the ArchRule fields in com.MyDomainRules and apply them on all src/main classes in com.myDomain package-->

                            <apply-on>
                                <package>com.myDomain</package>
                            </apply-on>
                        </configurable-rule>

                        <configurable-rule class="com.MyDomainSecondSetOfRules">

                            <!-- will take only checkA and checkB rules from com.MyDomainSecondSetOfRules (and fail if they are not ArchRule objects), and apply them on all src/test classes under
                            com.myDomain package-->

                            <checks>
                                <check>checkA</check>
                                <check>checkB</check>
                            </checks>

                            <apply-on>
                                <package>com.myDomain</package>
                                <scope>test</scope>
                            </apply-on>
                        </configurable-rule>

                    </rules>
```

```configurable-rule``` could evolve fairly easily after, we could add more fields if required. 

@arpitgarg9168 , what do you think ? possible ?

**Comment by arpitgarg9168** [comment]
@vincent-fuchs Yes I believe it's possible and it makes this plugin very flexible except the part that more number of configurable rules, larger will be the pom.xml

**Comment by vincent-fuchs** [comment]
> @vincent-fuchs Yes I believe it's possible and it makes this plugin very flexible except the part that more number of configurable rules, larger will be the pom.xml

yes, config in pom.xml may be larger, but it's not a big deal. If people want it shorter in pom.xml, they'll have to pre-configure them in code. You can't have your cake and eat it ;-)

**Comment by vincent-fuchs** [comment]
hi @arpitgarg9168 , any update on this ? We've added new rules, so it would be nice to give a release. Will it include your changes ? that is the question ;-)

**Comment by vincent-fuchs** [comment]
@codecholeric , we've made some changes. We still have some improvements to do (looks like as part of some refactoring, code coverage dropped and some use cases are not covered anymore) : we'll take care of them before doing an official release, hopefully in a few days. 
But you can try to checkout master and build 2.0.0-SNAPSHOT locally to give it a try. Documentation has been updated : https://github.com/societe-generale/arch-unit-maven-plugin#add-a-rule-and-share-it-across-projects

**Comment by codecholeric** [comment]
@vincent-fuchs cool :smiley: I'm really sorry that it took me so long to find time to look at this. Now the world has moved on... But I'll still add my notes.

First of all it worked well to execute a custom rule when I tried it, very much like how I imagined reusing fields of type `ArchRule` :+1: 

I've just tried it and looked at the code a little, so I would share some of my points:

* As far as I see there is no way to test scope `compile` and `test` together, AFAIS? I guess this is consistent with Maven's defaults, but the implication is that testing a rule on both main and test classes will now need two separate configurations of the same rule, if I'm not mistaken. However this is probably not a common case anyway, just wanted to note it.
* I've noticed that I can write any `check` and if there is no matching rule, it will just silently ignore the argument. Wouldn't it be better to fail or at least log a warning? Imagine someone would rename the field, then the test would just silently be green for all times...
* I saw that you evaluate all methods returning an `ArchCondition`. To be consistent with the JUnit support it would need to support methods like `static void myArchTest(JavaClasses importedClasses) {...}` where the imported classes are passed in. At least that is the supported `@ArchTest` way.
* It would probably make sense to reuse the imported classes for all different checks, at the moment it seems that `importAllClassesInPackage(projectPath, packageOnRuleToApply)` is invoked several times which will cost a lot of performance if the project is bigger and the number of `checks` increased.

If you want I could try to add a small PR to address my issues? (instead of just smart talking :wink:)

**Comment by vincent-fuchs** [comment]
hi @codecholeric , good to hear from you !

for the first point 

> As far as I see there is no way to test scope compile and test together

you're correct, and I think this is acceptable : in the very few cases for which you would need it, you would have to duplicate the config.

For the rest, yes, PRs are always welcome ;-) I think we could benefit from your experience on the last point 
> reuse the imported classes for all different checks

 as we have a similar issue https://github.com/societe-generale/arch-unit-maven-plugin/issues/13 in which we have difficulties controlling which classes are analyzed (more than we expect). @arpitgarg9168 , any progress on it ?
