### ISSUE TITLE
Does not scan classes of POM modules

### ISSUE THREAD

**Issue by croesch** [societe-generale/arch-unit-maven-plugin#19]
## Summary

If you use POM modules, the ArchUnit Maven Plugin does not search the correct path.

## Type of Issue
It is a : 
 - [x] bug
 - [ ] request
 - [ ] question regarding the documentation

## Motivation
If you have your project separated into different modules and define ArchUnit Maven Plugin in the root, then the module classes are not scanned.

## Current Behavior

It looks like ArchUnit Maven Plugin by default searches `./target` if you don't specify another directory in the plugin's configuration.

## Expected Behavior

IMO the plugin should always use the configured values for build directory, output directory and test output directory.

This would not only allow to use the plugin with module builds but also allow using the `-f` switch of Maven (which currently also seems to break the ArchUnit Maven Plugin).

## Steps to Reproduce (for bugs)

1. Create a POM with a rule and two modules.
1. Place code in that modules that would not pass the specified rules
1. Run `mvn clean verify`

## Your Environment

Using Maven 3.6.1 and the plugin's newest 2.2.0 release.

**Comment by croesch** [comment]
@vincent-fuchs what do you think about the direction I'm going with the latest commit?

Please ignore the tests for the review at the moment - I'm experimenting with tests and didn't separate it. If you'd accept such a breaking (API for configurable rules) change, I'll fix the tests and create a clean PR.

**Comment by vincent-fuchs** [comment]
I tried to reproduce on one of my projects, but for me it works. 

please try to checkout https://github.com/societe-generale/ci-droid-tasks-consumer and introduce a violation, like a System.out.println in a class.. for me the build fails (with maven 3.5.4)

can you please try and confirm ?

**Comment by croesch** [comment]
Thanks very much @vincent-fuchs for trying to reproduce!

I found that my configuration was missing `<projectPath>${project.build.directory}</projectPath>`.

This fixes most of my problems. The only thing is that projects changing the output directory or test output directory are able to bypass Arch Unit Maven Plugin:
```
  <build>
    <outputDirectory>/tmp/classes</outputDirectory>
    <testOutputDirectory>/tmp/test-classes</testOutputDirectory>
  </build>
```

If these folders reside outside your build directory or are named different, then the plugin fails to detect that. So the suggested refactoring still mitigates these type of issues.

**Comment by vincent-fuchs** [comment]
ok, why not.. but out of curiosity, why don't you follow maven standards in your project ? is it a very common use case ?

**Comment by vincent-fuchs** [comment]
also, shouldn't we rename this PR ? like "using Maven build values for outputDirectory / testOutputDirectory "

**Comment by croesch** [comment]
As commented in #20 I think at least the refactoring regarding the tests (that I've tested) could be worth to work on. Maybe it helps testing issues like #22.

I agree that this issue is not reflecting it's content anymore. Shall I close this issue and just open separate PRs if I finish my work on the branch?

Also I agree on using maven standards in projects as a good habit ;-) Usually I see two use cases for specifying different output directories

1. Moving output/test directories outside of target temporarily to bypass performance / write issues on the hardware
2. Some combinations of plugins / thirdparty systems that work on the output and are less configurable than the Maven build. I can give some examples of that but basically it's the result of migrating a project more or less 1:1 to Maven in a way you _can_ but maybe should not do it ;-)

**Comment by vincent-fuchs** [comment]
yes please, let's close this one and open a new one giving proper context. scanning of pom projects is about to be fixed in #25

**Comment by daniel-shuy** [comment]
Why does the `projectPath` default to `.target` instead of `${project.build.directory}`? If `projectPath` defaults to `${project.build.directory}`, then aggregate POMs no longer need to explicitly configure `projectPath`

**Comment by vincent-fuchs** [comment]
@daniel-shuy : I recommend you open another issue rather than commenting on something closed for one year. see https://github.com/societe-generale/arch-unit-maven-plugin/pull/39/files , I think next version will address your concern
