### ISSUE TITLE
Trying to scan modules with packaging `pom`

### ISSUE THREAD

**Issue by khmarbaise** [societe-generale/arch-unit-maven-plugin#22]
## Summary

In a multi module build which contains modules which have packaging `pom`. Basic example  is the root of a multi module build and maybe other children could 
be defined with `<packaging>pom</packaging>`. 

## Type of Issue
It is a : 
 - [ ] bug
 - [x] request
 - [ ] question regarding the documentation

## Current Behavior
The current behaviour is that it produces a warning like this for each module which `<packaging>pom</packaging>`
```
[INFO] --- arch-unit-maven-plugin:2.2.0:arch-test (default) @ xyz-parent ---
[WARNING] classpath ..../target/test-classes doesn't exist..
```
which is a litte bit misleading cause modules which have been defined `<packaging>pom</packaging>` could not have code which would be compiled etc.

## Expected Behavior
Based on the convention in Maven there should not be a WARNING for a module which is defined with `<packaging>pom</packaging>` cause it could not contain code at all.

It would also be a good idea to have a configuration which could be turned on to support edge cases where people define life cycle bindings in a module with `<packaging>pom</packaging>` on their own.

## Steps to Reproduce (for bugs)
Create a simple multi module build which contains a parent and two children. For the parent you will get the described WARNING.

## Your Environment
* Version used: 2.2.0
* OS and version: MacOS / JDK 11.0.3

**Comment by vincent-fuchs** [comment]
@khmarbaise , thanks for opening this, I agree it should be fixed.

I created a PR with the simplest fix possible, but I am struggling to have unit test it. Given your profile, I am sure you have an idea on what's the simplest way to build programmatically a pom.xml representation and tweak its packaging before "executing" it ;-) 

any pointers I could look at ?

**Comment by khmarbaise** [comment]
I have made PR which I'm not 100% ok with cause I can't correctly test the logging calls. This can be improved if #20 is done. Then we could use an interceptor to catch the logging output and check that also ....to make the test more reliable.
