### ISSUE TITLE
How to import package in JAR?

### ISSUE THREAD

**Issue by daniel-shuy** [societe-generale/arch-unit-maven-plugin#35]
How can I configure `arch-unit-maven-plugin` to include JARs for a rule? It seems to imply `ImportOption.DoNotIncludeJars` by default.

**Comment by vincent-fuchs** [comment]
I am not sure about the `ImportOption.DoNotIncludeJars` but it would make sense : we usually test the code when we build it ; Once it's built and available in a jar, it's considered good to be used by others. 
If we started testing the code within the jars, it would be a never ending story..
