### ISSUE TITLE
2.6.x no longer works with aggregate POM

### ISSUE THREAD

**Issue by daniel-shuy** [societe-generale/arch-unit-maven-plugin#40]
## Summary

Before version 2.6.x, if the `projectPath` is not specified, if the plugin is run from the aggregate POM level, it will default to `/target`, relative to the path the plugin is run from, in this case the aggregate POM level instead of the module level (eg. `/target` instead of `/module/target`), which will fail. The workaround was to explicitly configure `projectPath` as `${project.build.directory}`, which would cause it to run relative to the project base directory, regardless of where the plugin was run from.

With version 2.6.x, #39 is automatically getting the output directory and test output directory from [Build#getOutputDirectory()](https://maven.apache.org/ref/3.5.0/apidocs/org/apache/maven/model/Build.html#getOutputDirectory()) and [Build#getTestOutpuDirectory](https://maven.apache.org/ref/3.5.0/apidocs/org/apache/maven/model/Build.html#getTestOutputDirectory()), which is great, however both of these paths are still used relative to the path the plugin was run from. Hence if the plugin is run from the aggregate POM level, it will again use the wrong path (`/target` instead of `/module/target`). And since `projectPath` is removed, there is currently no workaround for this as well.

A solution would be to resolve the output directory and test output directory to the project base directory, which can be obtained using [MavenProject#getBasedir()](https://maven.apache.org/ref/3.5.0/apidocs/org/apache/maven/project/MavenProject.html#getBasedir()).

If you want, I can create a PR for this.

## Type of Issue

It is a : 
 - [x] bug
 - [ ] request
 - [ ] question regarding the documentation

## Your Environment

* Version used: 2.6.1

**Comment by vincent-fuchs** [comment]
Hi @daniel-shuy , thanks for raising this.
 
I've tried to fix it in https://github.com/societe-generale/arch-unit-maven-plugin/tree/issue40 , but I don't think it works.. 
when I run `mvn com.societegenerale.commons:arch-unit-maven-plugin:2.6.2-SNAPSHOT:arch-test `at the root of a multi-module project, it doesn't work.

is it somethink like this you have in mind, to make it work in all cases ?

**Comment by daniel-shuy** [comment]
Oh, my bad, I thought #39 was part of `2.6.1`. Turns out [Build#getOutputDirectory()](https://maven.apache.org/ref/3.5.0/apidocs/org/apache/maven/model/Build.html#getOutputDirectory()) and [Build#getTestOutputDirectory()](https://maven.apache.org/ref/3.5.0/apidocs/org/apache/maven/model/Build.html#getTestOutputDirectory()) return absolute paths, so #39 actually fixes this issue.

**Comment by vincent-fuchs** [comment]
I'll release 2.6.2 shortly so that #39 is easily available
