### ISSUE TITLE
Change log level from info to warning when noFailOnError=true

### ISSUE THREAD

**Issue by guerrillalg** [societe-generale/arch-unit-maven-plugin#58]
## Summary
When there are some errors, however noFailOnError is set to true. It should log errors as Warning, so that developers will actually see it.

## Type of Issue
It is a : 
 - [ ] bug
 - [X] request
 - [ ] question regarding the documentation

## Motivation
When there are some validation errors, and the property noFailOnError, an error is logged on the info level. Thus, it can be easily lost, instead it should be logged as warning. This way it would bring attention. 
Change is trivial, should be done on the line:
https://github.com/societe-generale/arch-unit-maven-plugin/blob/b5fb077aed2ab20c07cf26d812a5a1698209143a/src/main/java/com/societegenerale/commons/plugin/maven/ArchUnitMojo.java#L119

## Current Behavior
When there are some validation errors, it is logged as info:
[INFO] Merging properties: The following properties have been overwritten by system properties: {noFailOnError=true}
[INFO] applying rules on 12 classe(s). To see the details, enable debug logs
SKIPPED
[INFO] ArchUnit Maven plugin reported architecture failures listed below :Rule Violated - SKIPPED
[INFO] 

## Expected Behavior
When there are some validation errors, it should be logged as warning:
[INFO] Merging properties: The following properties have been overwritten by system properties: {noFailOnError=true}
[INFO] applying rules on 12 classe(s). To see the details, enable debug logs
SKIPPED
[WARNING] ArchUnit Maven plugin reported architecture failures listed below :Rule Violated - SKIPPED
[INFO] 

## Steps to Reproduce (for bugs)
Set property  <noFailOnError>true</noFailOnError>
Make sure there are some validation errors.

## Your Environment

* Version used: 3.0.0
* OS and version: Any
* Version of libs used:

**Comment by vincent-fuchs** [comment]
available in 4.0.0 , please give it a try !

**Comment by vincent-fuchs** [comment]
and available in https://github.com/societe-generale/arch-unit-maven-plugin/releases/tag/archUnit_maven_plugin_3.0.1
