### ISSUE TITLE
Skip analysis for projects without source files

### ISSUE THREAD

**Issue by purnhar** [societe-generale/arch-unit-maven-plugin#66]
## Summary

If no source files are found in a module of a multi module project, no analysis should be done (e.g. in modules which just assemble war files or docker images).

## Type of Issue
It is a : 
 - [ ] bug
 - [x] request
 - [ ] question regarding the documentation

## Motivation

The plugin is used in a multi module project and defined in the root POM. Some of our modules only contain test code (integration tests) or they don't contain any java code at all (e.g. modules for building docker images). When building these modules the plugin adds all possible directories for analysis and therefore analyses the whole classpath of our application (including 3rd party libs). Unfortunately this behavior can't be switched off and the plugin definition has to be overridden in the client modules.

It would be very helpful to have the possibility to switch off this behavior in the plugin configuration.

## Your Environment

* Version used: 3.0.0
* OS and version:
* Version of libs used:

**Comment by vincent-fuchs** [comment]
Hi,

This is the intended behavior. The alternate is worse IMHO : people could misconfigure something, believe that the test runs fine, while actually nothing was analyzed. 

Overriding the archunit config in the submodules that don't need it is a cheap way to avoid this.

**Comment by purnhar** [comment]
This is the reason why I didn't ask to remove this behavior completely but to be able to switch it off explicitly. We have a very big module hierarchy and additionally very many projects using our pom definition as parent pom. Thats why we cannot just add a plugin configuration to all affected submodules.

**Comment by vincent-fuchs** [comment]
ok. If you're really interested in that feature, please open a PR in https://github.com/societe-generale/arch-unit-build-plugin-core (making sure the current behavior is still the default) and in  https://github.com/societe-generale/arch-unit-maven-plugin (to set the flag) : I will review them

**Comment by purnhar** [comment]
Thank you. Would it be possible to reintegrate the changes to the 3.x line? We are currently on Java 17 and 4.0 is only working on Java 21. I could provide pull requests for both branches.

Or maybe you could switch back the main branch to Java 17 so it could be used by more (not so current) projects.

**Comment by vincent-fuchs** [comment]
yes, please submit for the 2 branches, and I will do 2 releases

**Comment by purnhar** [comment]
It created the necessary pull requests for 3.x and 4.x on core and maven plugin. I tried to keep the changes as small as possible. Looking forward for your feedback.
